import { type AbstractIntlMessages, NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { AppProvider } from "~/components/providers/AppProvider";
import { LANGUAGE, type Language } from "~/navigation";
import "~/styles/globals.css";
import { cn } from "~/utils/utils";

export const metadata = {
  title: "Welcome to website",
  description: "Generated by create-nx-workspace",
};

export const generateStaticParams = () => {
  return Object.values(LANGUAGE).map(lang => ({ lang }));
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: { lang: Language };
}) {
  const { children, params } = await props;
  const { lang } = await params;
  setRequestLocale(lang);
  let messages: AbstractIntlMessages = await getMessages();
  try {
    messages = (await import(`messages/${lang}.json`)).default;
  } catch (_error) {
    notFound();
  }

  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(
          "bg-gray text-secondary dark:bg-gray-dark dark:text-secondary-darkMode flex min-h-[100dvh] flex-col"
        )}
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100dvh",
        }}
      >
        <NextIntlClientProvider locale={lang} messages={messages}>
          <AppProvider>
            <main>{children}</main>
          </AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
