# OUTPUT_LANG_INDEX start from 0
generator-localization-admin:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1AOqyRVRaroE1sPv7PCEK00zz_SPPGb-9_du2jAovblk GID_ID=User OUTPUT_FOLDER=../messages/en.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=4 SPREADSHEET_ID=1AOqyRVRaroE1sPv7PCEK00zz_SPPGb-9_du2jAovblk GID_ID=User OUTPUT_FOLDER=../messages/ja.json